import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white flex justify-center">
        <div
          className="
            w-full h-screen bg-gray 
            md:h-[calc(100vh-1rem*2)] md:w-[390px] md:border-gray-700 md:rounded-xl md:shadow-xl 
            md:mt-4 md:overflow-hidden md:relative
          "
        >
          {children}
        </div>
      </body>
    </html>
  );
}
